save_loc: "NAF_logs/real_exp_optuna"
exp_name: "Real_exp_param_0_1"
coor_base: "Pyroomacoustics/outputs/real_exp_8720_NAF"
spec_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/magnitudes"
phase_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/phases"
mean_std_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/magnitude_mean_std"
phase_std_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/phase_std"
minmax_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/minmax"
wav_base: "Pyroomacoustics/outputs/real_exp_8720_NAF/raw"
split_loc: "Pyroomacoustics/outputs/real_exp_8720_NAF/train_test_split"
gpus: 1
dir_ch: 1
max_len: 15
layers: 8
layers_residual: 0
features: 512
epochs: 50
reg_eps: 0.0
lr_init: 0.0005
lr_decay: 0.1
phase_alpha: 1.0
mag_alpha: 1.0
pixel_count: 2000
batch_norm: "none"
activation_func_name: "default"
