activation_func_name: default
batch_norm: none
coor_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF
dir_ch: 1
epochs: 300
exp_name: Real_env_param_88_1
features: 64
gpus: 1
layers: 9
layers_residual: 3
lr_decay: 0.08249959146749207
lr_init: 0.002112154539589612
mag_alpha: 1.0
max_len: 15
mean_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/preprocess/magnitude_mean_std
minmax_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/minmax
phase_alpha: 8.971486179370158
phase_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/preprocess/phases
phase_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/preprocess/phase_std
pixel_count: 2688
reg_eps: 0.10014438030958252
save_loc: NAF_logs/real_env_best
spec_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/preprocess/magnitudes
split_loc: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/train_test_split
wav_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_16kHz_standard_NAF/raw
