activation_func_name: default
batch_norm: none
coor_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF
dir_ch: 8
epochs: 300
exp_name: Pra_ch_param_94_1
features: 256
gpus: 1
layers: 5
layers_residual: 1
lr_decay: 0.05068153534729091
lr_init: 0.003847547489461904
mag_alpha: 1.0
max_len: 15
mean_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/preprocess/magnitude_mean_std
minmax_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/minmax
phase_alpha: 4.312744069052749
phase_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/preprocess/phases
phase_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/preprocess/phase_std
pixel_count: 2777
reg_eps: 0.07909815367439668
save_loc: NAF_logs/pra_ch_best
spec_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/preprocess/magnitudes
split_loc: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/train_test_split
wav_base: Pyroomacoustics/outputs/real_env_avr_16kHz_centered_NAF/raw
