activation_func_name: default
batch_norm: none
coor_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF
dir_ch: 1
epochs: 300
exp_name: Pra_param_99_1
features: 64
gpus: 1
layers: 4
layers_residual: 2
lr_decay: 0.24902999941702444
lr_init: 4.751320720179008e-05
mag_alpha: 1.0
max_len: 15
mean_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/magnitude_mean_std
minmax_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/minmax
phase_alpha: 7.397822012469649
phase_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/phases
phase_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/phase_std
pixel_count: 2147
reg_eps: 0.053167569016486366
save_loc: NAF_logs/pra_best
spec_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/magnitudes
split_loc: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/train_test_split
wav_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/raw
