activation_func_name: default
batch_norm: none
coor_base: Pyroomacoustics/outputs/real_exp_8720_NAF
dir_ch: 1
epochs: 300
exp_name: Real_exp_param_103_1
features: 64
gpus: 1
layers: 8
layers_residual: 3
lr_decay: 0.11166502983663565
lr_init: 2.2820708439386187e-05
mag_alpha: 1.0
max_len: 15
mean_std_base: Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/magnitude_mean_std
minmax_base: Pyroomacoustics/outputs/real_exp_8720_NAF/minmax
phase_alpha: 2.6181303658851487
phase_base: Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/phases
phase_std_base: Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/phase_std
pixel_count: 1931
reg_eps: 0.12236333952091417
save_loc: NAF_logs/real_exp_best
spec_base: Pyroomacoustics/outputs/real_exp_8720_NAF/preprocess/magnitudes
split_loc: Pyroomacoustics/outputs/real_exp_8720_NAF/train_test_split
wav_base: Pyroomacoustics/outputs/real_exp_8720_NAF/raw
