activation_func_name: default
batch_norm: none
coor_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF
dir_ch: 8
epochs: 300
exp_name: Real_env_ch_param_93_1
features: 256
gpus: 1
layers: 5
layers_residual: 0
lr_decay: 0.22060783483793625
lr_init: 0.004788863334097811
mag_alpha: 1.0
max_len: 15
mean_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/magnitude_mean_std
minmax_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/minmax
phase_alpha: 1.6991936011670195
phase_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/phases
phase_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/phase_std
pixel_count: 3430
reg_eps: 0.06548052899343096
save_loc: NAF_logs/real_env_ch_best
spec_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/magnitudes
split_loc: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/train_test_split
wav_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/raw
