activation_func_name: default
batch_norm: none
coor_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF
dir_ch: 8
epochs: 300
exp_name: Real_exp_ch_param_43_1
features: 1024
gpus: 1
layers: 6
layers_residual: 2
lr_decay: 0.13423637920822107
lr_init: 0.00033227729957306895
mag_alpha: 1.0
max_len: 15
mean_std_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/preprocess/magnitude_mean_std
minmax_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/minmax
phase_alpha: 0.7661073441672404
phase_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/preprocess/phases
phase_std_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/preprocess/phase_std
pixel_count: 627
reg_eps: 0.1236700170496434
save_loc: NAF_logs/real_exp_ch_best
spec_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/preprocess/magnitudes
split_loc: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/train_test_split
wav_base: Pyroomacoustics/outputs/real_exp_8720_centered_NAF/raw
